// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SamverkandeAPI.Data;

namespace SamverkandeAPI.Migrations.AnnonsDb
{
    [DbContext(typeof(AnnonsDbContext))]
    partial class AnnonsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SamverkandeAPI.Models.Ads", b =>
                {
                    b.Property<int>("Ad_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Ad_AnnonsPris")
                        .HasColumnType("int");

                    b.Property<int>("Ad_Annonsor")
                        .HasColumnType("int");

                    b.Property<string>("Ad_Innehall")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ad_Rubrik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ad_VaransPris")
                        .HasColumnType("int");

                    b.HasKey("Ad_Id");

                    b.ToTable("Ads");
                });

            modelBuilder.Entity("SamverkandeAPI.Models.Annonsorer", b =>
                {
                    b.Property<int>("An_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("An_Efternamn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("An_Epost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("An_FOrt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("An_FPostnummer")
                        .HasColumnType("int");

                    b.Property<string>("An_Foretagsnamn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("An_Fornamn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("An_Mobil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("An_Organisationsnummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("An_Personnummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("An_UOrt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("An_UPostnummer")
                        .HasColumnType("int");

                    b.Property<string>("An_Utdelningsadress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fakturaadress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("An_Id");

                    b.ToTable("Annonsorer");
                });
#pragma warning restore 612, 618
        }
    }
}
